name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 20:30 UTC - UTC+3:30 Midnight
    - cron: "30 20 * * *"
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_UPDATED_DATE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROJECTS: "False"
          SHOW_OS: "False"
          SHOW_LOC_CHART: "False"
